name: Bug report
description: Report a reproducible problem
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please provide enough detail to reproduce quickly.
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the current behavior and expected behavior.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      placeholder: |
        1. Run ...
        2. Send request ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs, traceback, or screenshots.
  - type: input
    id: version
    attributes:
      label: Commit / version
      placeholder: main@<sha>
